# Generated by Django 5.0.6 on 2024-06-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.AutoField(db_column='idKor', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('ime', models.CharField(max_length=256)),
                ('prezime', models.CharField(blank=True, max_length=256, null=True)),
                ('pib', models.IntegerField(blank=True, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tip', models.CharField(max_length=1)),
                ('datumrodj', models.DateField(blank=True, db_column='datumRodj', null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poruka',
            fields=[
                ('idpor', models.AutoField(db_column='idPor', primary_key=True, serialize=False)),
                ('redbr', models.CharField(db_column='redBr', max_length=45)),
                ('tekst', models.CharField(max_length=2000)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'poruka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prepiska',
            fields=[
                ('idpre', models.AutoField(db_column='idPre', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prepiska',
                'managed': False,
            },
        ),
    ]
