# Generated by Django 5.0.6 on 2024-06-08 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idkor', models.AutoField(db_column='idKor', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ime', models.CharField(max_length=255)),
                ('prezime', models.CharField(blank=True, max_length=255, null=True)),
                ('pib', models.IntegerField(blank=True, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tip', models.CharField(max_length=1)),
                ('datumrodj', models.DateField(blank=True, db_column='datumRodj', null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('drzava', models.CharField(max_length=256)),
                ('kontinent', models.CharField(max_length=256)),
                ('idlok', models.AutoField(db_column='idLok', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lokacija',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('oblast', models.CharField(max_length=256)),
                ('idobl', models.AutoField(db_column='idObl', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'oblast',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('idakt', models.AutoField(db_column='idAkt', primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255)),
                ('brmesta', models.IntegerField(db_column='brMesta')),
                ('datumod', models.DateField(db_column='datumOd')),
                ('datumdo', models.DateField(db_column='datumDo')),
                ('datumrok', models.DateField(db_column='datumRok')),
                ('mesto', models.CharField(max_length=255)),
                ('opis', models.CharField(blank=True, max_length=3000, null=True)),
                ('idorg', models.ForeignKey(db_column='idOrg', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('lokacija', models.ForeignKey(db_column='lokacija', on_delete=django.db.models.deletion.DO_NOTHING, to='budivolonter.lokacija')),
            ],
            options={
                'db_table': 'aktivnost',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prepiska',
            fields=[
                ('idpre', models.AutoField(db_column='idPre', primary_key=True, serialize=False)),
                ('idkor1', models.ForeignKey(db_column='idKor1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idkor2', models.ForeignKey(db_column='idKor2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prepiska_idkor2_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prepiska',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('idpri', models.AutoField(db_column='idPri', primary_key=True, serialize=False)),
                ('pismo', models.CharField(max_length=2000)),
                ('rezime', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('preporukavol', models.CharField(blank=True, db_column='preporukaVol', max_length=1, null=True)),
                ('preporukaorg', models.CharField(blank=True, db_column='preporukaOrg', max_length=1, null=True)),
                ('komvol', models.CharField(blank=True, db_column='komVol', max_length=1000, null=True)),
                ('komorg', models.CharField(blank=True, db_column='komOrg', max_length=1000, null=True)),
                ('idakt', models.ForeignKey(db_column='idAkt', on_delete=django.db.models.deletion.DO_NOTHING, to='budivolonter.aktivnost')),
                ('idvol', models.ForeignKey(db_column='idVol', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prijava',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pripada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idakt', models.ForeignKey(db_column='idAkt', on_delete=django.db.models.deletion.CASCADE, to='budivolonter.aktivnost')),
                ('idobl', models.ForeignKey(db_column='idObl', on_delete=django.db.models.deletion.CASCADE, to='budivolonter.oblast')),
            ],
            options={
                'db_table': 'pripada',
                'managed': True,
                'unique_together': {('idakt', 'idobl')},
            },
        ),
        migrations.AddField(
            model_name='oblast',
            name='aktivnosti',
            field=models.ManyToManyField(through='budivolonter.Pripada', to='budivolonter.aktivnost'),
        ),
        migrations.AddField(
            model_name='aktivnost',
            name='oblasti',
            field=models.ManyToManyField(through='budivolonter.Pripada', to='budivolonter.oblast'),
        ),
        migrations.CreateModel(
            name='Vestina',
            fields=[
                ('idves', models.AutoField(db_column='idVes', primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=256)),
                ('idakt', models.ForeignKey(db_column='idAkt', on_delete=django.db.models.deletion.DO_NOTHING, to='budivolonter.aktivnost')),
            ],
            options={
                'db_table': 'vestina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZanimaGa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkor', models.ForeignKey(db_column='idKor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idobl', models.ForeignKey(db_column='idObl', on_delete=django.db.models.deletion.CASCADE, to='budivolonter.oblast')),
            ],
            options={
                'db_table': 'zanima_ga',
                'managed': True,
                'unique_together': {('idkor', 'idobl')},
            },
        ),
        migrations.AddField(
            model_name='oblast',
            name='korisnici',
            field=models.ManyToManyField(through='budivolonter.ZanimaGa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='oblasti',
            field=models.ManyToManyField(through='budivolonter.ZanimaGa', to='budivolonter.oblast'),
        ),
        migrations.CreateModel(
            name='Poruka',
            fields=[
                ('idpor', models.AutoField(db_column='idPor', primary_key=True, serialize=False)),
                ('redbr', models.CharField(db_column='redBr', max_length=45)),
                ('tekst', models.CharField(max_length=2000)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=1)),
                ('idsender', models.ForeignKey(db_column='idSender', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idpre', models.ForeignKey(db_column='idPre', on_delete=django.db.models.deletion.DO_NOTHING, to='budivolonter.prepiska')),
            ],
            options={
                'db_table': 'poruka',
                'managed': True,
                'unique_together': {('idpre', 'redbr')},
            },
        ),
    ]
